name: image-correlation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - rioxarray
  - geopandas
  - matplotlib
  - ipykernel
  - seaborn
  - netcdf4
  - autorift
  - pystac-client
  - odc-stac
  - planetary-computer
  - dask
